export const ActionType = {
  CHANGE_CITY: `CHANGE_CITY`,
  FETCH_OFFERS_LOADING: `FETCH_OFFERS_LOADING`,
  FETCH_OFFERS_RECEIVED: `FETCH_OFFERS_RECEIVED`,
  FETCH_OFFERS_FAILED: `FETCH_OFFERS_FAILED`,
  AUTHORIZATION: `AUTHORIZATION`,
  AUTHORIZATION_FAILED: `AUTHORIZATION_FAILED`,
  ACTIVE_OFFER: `ACTIVE_OFFER`,
  FETCH_REVIEWS_SUCCESS: `FETCH_REVIEWS_SUCCESS`,
  FETCH_REVIEWS_FAILED: `FETCH_REVIEWS_FAILED`,
  CHANGE_SORT: `CHANGE_SORT`,
  ACTIVE_PIN_OFFER_CHANGE: `ACTIVE_PIN_OFFER_CHANGE`,
  SENDING_REVIEWS: `SENDING_REVIEWS`,
  SENDING_REVIEWS_ERROR: `SENDING_REVIEWS_ERROR`,
  FAVORITE_LOADING: `FAVORITE_LOADING`,
  FAVORITE_RECEIVED: `FAVORITE_RECEIVED`,
  FETCH_FAVORITE_FAILED: `FETCH_FAVORITE_FAILED`
};
