export const ActionType = {
  CHANGE_CITY: `CHANGE_CITY`,
  FETCH_OFFERS_LOADING: `FETCH_OFFERS_LOADING`,
  FETCH_OFFERS_RECEIVED: `FETCH_OFFERS_RECEIVED`,
  FETCH_OFFERS_FAILED: `FETCH_OFFERS_FAILED`,
  AUTHORIZATION_SUCCESS: `AUTHORIZATION_SUCCESS`,
  AUTHORIZATION_FAILED: `AUTHORIZATION_FAILED`,
  ACTIVE_OFFER: `ACTIVE_OFFER`
};
